name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        env:
          CHECK_PLATFORM_REQUIREMENTS: false
        with:
          args: analyse src/ --level=5
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
            php-version: '7.4'
            extensions: curl, sockets, iconv, json, ctype
      - name: Setup PCOV
        run: |
          vendor/bin/simple-phpunit
